version: '3.8'

services:
  mouad-java:

    build: .
    container_name: mouad-java-container
    ports:
      - "1015:1005"
    networks:
      - mouad-net

    depends_on:
      - postgres-sql

  postgres-sql:
    image: postgres
    container_name: postgres-sql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: mouad-demo
    ports:
      - "5432:5432"
    networks:
      - mouad-net

networks:
  mouad-net:
    driver: bridge
